# Generated by Django 4.1.2 on 2022-11-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="economy_num_places",
            field=models.IntegerField(null=True),
        ),
    ]
