# Generated by Django 4.1.2 on 2022-11-16 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0002_flight_economy_num_places"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="arrive_date",
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
