# Generated by Django 4.1.2 on 2022-11-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0003_flight_arrive_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="business_num_places",
            field=models.IntegerField(null=True),
        ),
    ]
